package com.ispt.offers;
// Generated 16.May.2012 19:03:55 by Hibernate Tools 3.2.1.GA

import com.ispt.adverts.Adverts;
import javax.faces.bean.ManagedBean;




/**
 * Offers generated by hbm2java
 */
@ManagedBean
public class Offers  implements java.io.Serializable {


     private Integer idoffers;
     private Adverts adverts;
     private int teklifVerenId;
     private int teklifAlanId;
     private String teklifMesaj;
     private String cevapMesaj;
     private Boolean okunmusmu;

    public Offers() {
    }

	
    public Offers(Adverts adverts, int teklifVerenId, int teklifAlanId) {
        this.adverts = adverts;
        this.teklifVerenId = teklifVerenId;
        this.teklifAlanId = teklifAlanId;
    }
    public Offers(Adverts adverts, int teklifVerenId, int teklifAlanId, String teklifMesaj, String cevapMesaj, Boolean okunmusmu) {
       this.adverts = adverts;
       this.teklifVerenId = teklifVerenId;
       this.teklifAlanId = teklifAlanId;
       this.teklifMesaj = teklifMesaj;
       this.cevapMesaj = cevapMesaj;
       this.okunmusmu = okunmusmu;
    }
   
    public Integer getIdoffers() {
        return this.idoffers;
    }    
    public void setIdoffers(Integer idoffers) {
        this.idoffers = idoffers;
    }
    public Adverts getAdverts() {
        return this.adverts;
    }    
    public void setAdverts(Adverts adverts) {
        this.adverts = adverts;
    }
    public int getTeklifVerenId() {
        return this.teklifVerenId;
    }    
    public void setTeklifVerenId(int teklifVerenId) {
        this.teklifVerenId = teklifVerenId;
    }
    public int getTeklifAlanId() {
        return this.teklifAlanId;
    }    
    public void setTeklifAlanId(int teklifAlanId) {
        this.teklifAlanId = teklifAlanId;
    }
    public String getTeklifMesaj() {
        return this.teklifMesaj;
    }    
    public void setTeklifMesaj(String teklifMesaj) {
        this.teklifMesaj = teklifMesaj;
    }
    public String getCevapMesaj() {
        return this.cevapMesaj;
    }
    public void setCevapMesaj(String cevapMesaj) {
        this.cevapMesaj = cevapMesaj;
    }
    public Boolean getOkunmusmu() {
        return this.okunmusmu;
    }    
    public void setOkunmusmu(Boolean okunmusmu) {
        this.okunmusmu = okunmusmu;
    }  


}


