package com.ispt.users;
// Generated 28.Nis.2012 07:11:54 by Hibernate Tools 3.2.1.GA



/**
 * Users generated by hbm2java
 */

public class Users  implements java.io.Serializable {


     private Integer idUsers;
     private String isim;
     private String soyisim;
     private String mail;
     private String telefon;
     private String adres;

    public Users() {
    }

    public Users(String isim, String soyisim, String mail, String telefon, String adres) {
       this.isim = isim;
       this.soyisim = soyisim;
       this.mail = mail;
       this.telefon = telefon;
       this.adres = adres;
    }
   
    public Integer getIdUsers() {
        return this.idUsers;
    }
    
    public void setIdUsers(Integer idUsers) {
        this.idUsers = idUsers;
    }
    public String getIsim() {
        return this.isim;
    }
    
    public void setIsim(String isim) {
        this.isim = isim;
    }
    public String getSoyisim() {
        return this.soyisim;
    }
    
    public void setSoyisim(String soyisim) {
        this.soyisim = soyisim;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }




}


