package com.ispt.deneme;
// Generated 28.Nis.2012 07:11:54 by Hibernate Tools 3.2.1.GA



/**
 * Deneme generated by hbm2java
 */
public class Deneme  implements java.io.Serializable {


     private Integer iddeneme;
     private String yas;

    public Deneme() {
    }

    public Deneme(String yas) {
       this.yas = yas;
    }
   
    public Integer getIddeneme() {
        return this.iddeneme;
    }
    
    public void setIddeneme(Integer iddeneme) {
        this.iddeneme = iddeneme;
    }
    public String getYas() {
        return this.yas;
    }
    
    public void setYas(String yas) {
        this.yas = yas;
    }




}


